excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://xJackTaylorx.github.io
title: xJackTaylorx
tagline: My Completely Boring And British Life
description: My Site, Which I Own, And The Only Thing I Own... Co-Owners May Be Joining
paginate: 5